# Generated by Django 5.0.6 on 2024-05-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
